# Generated by Django 3.2.5 on 2021-09-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date1', models.DateTimeField(auto_now=True, null=True)),
                ('date2', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.ImageField(null=True, upload_to='file')),
            ],
        ),
    ]
